local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: S3
  access_key_id: "AKIAVU56Z243KCKMWTMM"
  secret_access_key: "P6mI9KCAnoIYhnUfaFnNAyzUIpL7dAjkMvRs7hML"
  bucket: "bucket5app5jose"
  region: "us-east-1" # e.g. 'us-east-1'

